version : '3'

services:
  php:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
      - /var/log/apache2/app:/var/log/apache2/
    ports:
      - "8080:80"


  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: isitech
      MARIADB_USER: isitech
      MARIADB_PASSWORD: isitech
    ports:
      - "3306:3306"
    volumes:
        - ./dbvolume:/var/lib/mysql
    expose:
      - "3306"


  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
